#!/bin/bash

#SBATCH --partition=macmanes
#SBATCH --cpus-per-task=40
#SBATCH --mem 310Gb
#SBATCH --open-mode=append
#SBATCH --exclude=node117,node118,node139
#SBATCH --output RNAseqReadCount1.log
#SBATCH --mail-user=dmb1086@wildcats.unh.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

module unload linuxbrew/colsa
module load anaconda/colsa
conda activate /mnt/home/macmaneslab/dmb1086/software2/

##source ~/.bashrc
##conda activate mapping

#### Purpose: align reads to a genome and count them
### Inputs: path the genome fasta, path to genome gff file,
## Note: if files are not gzipped the "--readFilesCommand zcat" flag in STAR needs to be changed.
## Note: Script assumes index of genome is in: ./STAR_index

DIR=$(pwd)
GENOME=$1
GFF=$2
READ_DIR=$3
SUFFIX=$4

echo "Genome: $GENOME"
echo "gff: $GFF"
echo "Reads directory: $READ_DIR"
echo "Reads suffix: $SUFFIX"

# make a directory for star read mapping
mkdir $DIR/STAR_mapped1

# make a directory for star genome index
# mkdir $DIR/STAR_index

#Index genome with STAR
#STAR --runMode genomeGenerate \
#--genomeDir $DIR/STAR_index \
#--genomeFastaFiles $GENOME \
#--runThreadN 40 \
#--limitGenomeGenerateRAM 70744733397 \
#--sjdbOverhang 149 \
#--genomeChrBinNbits 18 \
#--sjdbGTFfile $GFF \
#--sjdbGTFtagExonParentTranscript Parent

#####################
##### map reads #####
#####################

# list all samples to map
samples=$(basename -a ${READ_DIR}/*1$SUFFIX | sed "s/1${SUFFIX}//g")

echo Mapping these samples: $samples

# map reads with STAR
for sample in $samples
do
# what sample is currently being mapped?
echo Mapping $sample

# map with star
STAR --runMode alignReads \
--genomeDir $DIR/STAR_index \
--readFilesIn ${READ_DIR}/${sample}1${SUFFIX} ${READ_DIR}/${sample}2${SUFFIX} \
--runThreadN 40 \
--outFilterMultimapNmax 20 \
--readFilesCommand zcat \
--outFilterMismatchNmax 10 \
--outFilterScoreMinOverLread 0 \
--outFilterMatchNminOverLread 0.3 \
--quantMode GeneCounts \
--outFileNamePrefix ${DIR}/STAR_mapped1/${sample} \
--outSAMtype BAM Unsorted \
--genomeLoad LoadAndKeep
done


#######################
##### count reads #####
#######################

# count reads with htseq-count
echo Counting genes with htseq-count for these samples: $samples

for sample in $samples
do
htseq-count -s no -f bam -t exon -i Parent $DIR/STAR_mapped1/${sample}Aligned.out.bam $GFF > $DIR/STAR_mapped1/${sample}gene.counts
done
